export default [
  {
    id: '1',
    imgUrl: '',
    title: "Women's Work-Life Balance for Wellbeing",
    speaker: 'Sarah Lichter',
    price: '95 EUR',
    duration: '2h 30min',
    type: 'featured_course',
  },
  {
    id: '2',
    imgUrl: '',
    title: 'Healthy and Balanced Nutrition for Wellbeing',
    speaker: 'Astrid Jackobsen',
    price: '140 EUR',
    duration: '3h 10min',
    status: 'startCourse',
    type: 'my_course',
  },
  {
    id: '3',
    imgUrl: '',
    title: 'Positive Psychology and Emotional Management',
    speaker: 'Johanna Harvey',
    price: '95 EUR',
    duration: '2h 40min',
    type: 'featured_course',
  },
  {
    id: '4',
    imgUrl: '',
    title: 'Back to normal - handling breakup or divorce',
    speaker: 'Johanna Harvey',
    price: '190 EUR',
    duration: '2h 30min',
    status: 'inProgress',
    type: 'my_course',
  },
  {
    id: '5',
    imgUrl: '',
    title: 'Back to normal - handling breakup or divorce',
    speaker: 'Johanna Harvey',
    price: '190 EUR',
    duration: '2h 30min',
    type: 'featured_course',
  },
  {
    id: '6',
    imgUrl: '',
    title: 'Back to normal - handling breakup or divorce',
    speaker: 'Johanna Harvey',
    price: '190 EUR',
    duration: '2h 30min',
    status: 'completed',
    type: 'my_course',
  },
  {
    id: '7',
    imgUrl: '',
    title: 'Back to normal - handling breakup or divorce',
    speaker: 'Johanna Harvey',
    price: '190 EUR',
    duration: '2h 30min',
    type: 'featured_course',
  },
  {
    id: '8',
    imgUrl: '',
    title: 'Back to normal - handling breakup or divorce',
    speaker: 'Johanna Harvey',
    price: '190 EUR',
    duration: '2h 30min',
    status: 'completed',
    type: 'my_course',
  },
  {
    id: '9',
    imgUrl: '',
    title: 'Back to normal - handling breakup or divorce',
    speaker: 'Johanna Harvey',
    price: '190 EUR',
    duration: '2h 30min',
    type: 'featured_course',
  },
];
